Initial Films web
kolengri/mentor-project-4yuri-v1 pull request #1
Opened 2021-01-03 14:23 UTC by Juris-coder

2021-01-03 14:24 UTC, kolengri requested changes

2021-01-03 14:24 UTC, kolengri commented on src/html/index.html
> -    test
Отличные изменения Юра

2021-01-31 17:38 UTC, merged

2021-02-01 23:27 UTC, kolengri commented
Мерджить не надо было :)

2021-02-01 23:46 UTC, kolengri reviewed
В целом ок. Завтра ещё посмотрю.  Обрати внимание на то что я написал и попробуй исправить эти недочеты в новом пул реквесте

2021-02-01 23:46 UTC, kolengri commented on src/html/index.html
> +      <div class="container_input">
В БЭМ методологии одинарное подчеркивание означает модификатор. Тут у тебя другой блок. Правильно будет ´container__input´

2021-02-01 23:46 UTC, kolengri commented on src/html/index.html
> +            <label for="List">List</label>
В for должно быть значение айпишника инпута, чтобы при клике на лейбл отрабатывало поле

2021-02-01 23:46 UTC, kolengri commented on src/html/index.html
> +            <label for="Posters">Posters</label>
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568214899

2021-02-01 23:46 UTC, kolengri commented on src/html/index.html
> +        <input id="filmsListInput" class="queryInput" name="query" placeholder="start typing...">
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568214899

2021-02-01 23:46 UTC, kolengri commented on src/js/filmAutocomplete.js
> +  const apiKey = '35c2658e0e706d145f4d4f7e995e368f';
Все инИциализации которые ты не будешь менять в последствии можно вынести из исполняемой функции.

2021-02-01 23:46 UTC, kolengri commented on src/js/filmAutocomplete.js
> +  const val = document.getElementById('filmsListInput');
Плохое название переменной. Лучше когда ссылаешься на элемент начинать с знака доллара и разумно называть переменную. $filmsListInput будет сильно лучше

2021-02-01 23:46 UTC, kolengri commented on src/js/filmAutocomplete.js
> +  const parentDiv = document.getElementById('parentDiv');
Название ссылки на элемент лучше начать со знака доллара

2021-02-01 23:46 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    const radioList = document.getElementById('radioList');
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568217193

2021-02-01 23:46 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    const radioPosters = document.getElementById('radioPosters');
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568217193

2021-02-01 23:46 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    const filmList = document.createElement('DIV');
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568217193

2021-02-01 23:46 UTC, kolengri commented on src/scss/main.scss
> +#parentDiv {
Старайся не стилизовать айдищники. Всегда стилизуй классы

2021-02-01 23:46 UTC, kolengri commented on src/scss/main.scss
> +.queryInput {
Что то у тебя формат названий прыгает. То классический, то ты использовал кебаб кейс, тут внезапно кэмелкейс. Оно имеет право на существование, но нужно придерживаться чего то одного. https://en.wikipedia.org/wiki/Naming_convention_(programming)

2021-02-01 23:46 UTC, kolengri commented on src/scss/main.scss
> +.queryInput:focus,
Это sass не css. Тут можно записать тоже самое через 
```
.classname {
  &:focus {...}
}

```
И плюс к этому: https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568218929

2021-02-01 23:46 UTC, kolengri commented on src/scss/main.scss
> +.queryInput:focus + .radio_div,
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568219033

2021-02-01 23:46 UTC, kolengri commented on src/scss/main.scss
> +#parentDiv {
Второй рад стилизуешь один и тот же айди. 

https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568218084

2021-02-01 23:46 UTC, kolengri commented on src/scss/main.scss
> +.image_container {
Теперь Снейк кейс появился :)

https://github.com/kolengri/mentor-project-4yuri-v1/pull/1#discussion_r568218929

2021-02-02 07:38 UTC, kolengri commented on src/js/filmAutocomplete.js
> +          const filmTitle = document.createElement('H4');
название ссылки на элемент лучше начинать со знака доллара

2021-02-02 07:38 UTC, kolengri commented on src/js/filmAutocomplete.js
> +          const image = document.createElement('IMG');
название ссылки на элемент лучше начинать со знака доллара

2021-02-02 07:38 UTC, kolengri commented on src/js/filmAutocomplete.js
> +          const listItem = document.createElement('DIV');
название ссылки на элемент лучше начинать со знака доллара

2021-02-02 07:38 UTC, kolengri commented on src/js/filmAutocomplete.js
> +          const filmYear = document.createElement('P');
название ссылки на элемент лучше начинать со знака доллара

2021-02-02 07:38 UTC, kolengri commented on src/js/filmAutocomplete.js
> +  const apiKey = '35c2658e0e706d145f4d4f7e995e368f';
И кстатит константы со всякими ключами или строками принятов писать в ВЕРТИКАЛЬНОМ_СНЕЙК_КЕЙСЕ

2021-02-02 07:39 UTC, kolengri commented on src/html/index.html
> +        <div class="radio_div">
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1/files#r568214080

2021-02-02 07:40 UTC, kolengri commented on src/html/index.html
> +        <div id="parentDiv"></div>
parentDiv очень не говорящее название айдишника. Нужно стараться придумать такое, чтобы смотрящий мог понять что ты пытаешься добиться добавляя его в код

2021-02-02 07:40 UTC, kolengri commented on src/html/index.html
> +    <div class="image_container"><img src="logo.png" alt="logo"></div>
https://github.com/kolengri/mentor-project-4yuri-v1/pull/1/files#r568214080

2021-02-02 07:40 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    const x = document.getElementsByClassName('autocomplete-items');
Название ссылки на элемент лучше начать со знака доллара

2021-02-02 07:42 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    const x = document.getElementsByClassName('autocomplete-items');
Название не говорит что находится в ссылке. Старайся не использовать магических букв, за исключением цикла `for(let i=0...)`. `i` классика, означает иттератор.

2021-02-02 07:43 UTC, kolengri commented on src/js/filmAutocomplete.js
> +        x[i].parentNode.removeChild(x[i]);
На самом деле в данном случае можно было бы использовать `x.forEach(...)` вместо цикла for.

2021-02-02 07:47 UTC, kolengri commented on src/js/filmAutocomplete.js
> +          listItem.innerHTML += "<input type='hidden' value='" + film.title + ' (' + film.vote_average.toFixed(1) + ')' + "'>";
На самом деле надежнее использовать `document.createElement(...)`, вместо генерации html как строки. Можно ошибиться и не заметить ошибки. Плюс с разными внешними стилями ты не знаешь как поведет себя текст рядом инпутом. Лучше обернуть текст в еще один див

2021-02-02 07:49 UTC, kolengri commented on src/js/filmAutocomplete.js
> +          const imageDiv = document.createElement('DIV');
название ссылки на элемент лучше начинать со знака доллара

2021-02-02 07:53 UTC, kolengri commented on src/js/filmAutocomplete.js
> +            image.setAttribute('src', 'https://media.istockphoto.com/vectors/internet-error-page-not-found-in-vertical-orientation-for-mobile-a-vector-id1252582562?s=612x612');
Ссылки на дефолтные картинки нужно вынести в константы за пределами основного кода.

`const IMAGE_PATH = ...`
`const NOT_FOUND_IMAGE_PATH = ...`

А потом использовать тут
```
if (resultFunc[i].poster_path) {
            image.setAttribute('src', `${IMAGE_PATH}${resultFunc[i].poster_path}`);
          } else {
            image.setAttribute('src', NOT_FOUND_IMAGE_PATH);
}
```

2021-02-02 07:55 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    xhr.open('GET', 'https://api.themoviedb.org/3/search/movie?api_key=' + apiKey + '&query=' + val.value, true);
Перенести ссылку на апи в константу
`const API_ENDPOINT = ...`

2021-02-02 07:56 UTC, kolengri commented on src/js/filmAutocomplete.js
> +        console.log('Unable to load data');
вообще тут должно быть `console.error` как миниум :) как максимум вывод ошибки на экран, если что-то не так

2021-02-02 07:56 UTC, kolengri commented on src/js/filmAutocomplete.js
> +    if (x) x = x.getElementsByTagName('div');
Знак доллара :)

2021-02-02 12:09 UTC, Juris-coder commented on src/js/filmAutocomplete.js
> +    const x = document.getElementsByClassName('autocomplete-items');
это так было на w3schools, я не менял :)